# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file if you have one
COPY requirements.txt .

# Run system dependencies
RUN apt-get update && apt-get install -y libsndfile1 libsndfile1-dev

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on Flask
EXPOSE 8000

# Copy the rest of the application code to the container
COPY . .

# Run the Flask application
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]