name: Python Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test Back-End
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest -v tests/tests.py

    - name: Send Mail
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} has ${{ job.status }}
        # email body as text
        body: |
          ${{ github.actor }} created commit:

          Commit message: ${{ github.event.commits[0].message }}
          
          Repository: ${{ github.repository }}

          Job: ${{ github.job }}
          
          Worflow: ${{ github.workflow }}

          Workflow Status: ${{ job.status }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        # comma-separated string, send email to
        to: pedro.henrique@hmit.com.br
        # from email name
        from: GitHub Actions Notifications

    - name: Send Telegram Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
             
          Commit message: ${{ github.event.commits[0].message }}
          
          Repository: ${{ github.repository }}
          
          Job: ${{ github.job }}

          Worflow: ${{ github.workflow }}

          Workflow Status: ${{ job.status }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  deploy_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: phenriqueol/voice-calculator-back-end

      - name: Calculate SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.short-sha.outputs.sha }}

      - name: Send Mail
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} has ${{ job.status }}
          # email body as text
          body: |
            Autor: ${{ github.actor }}

            Repository: ${{ github.repository }}

            Job: ${{ github.job }}
            
            Worflow: ${{ github.workflow }}

            Workflow Status: ${{ job.status }}

            Docker Image: ${{ steps.meta.outputs.tags }}-${{ steps.short-sha.outputs.sha }}
          # comma-separated string, send email to
          to: pedro.henrique@hmit.com.br
          # from email name
          from: GitHub Actions Notifications

      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Autor: ${{ github.actor }}
            
            Repository: ${{ github.repository }}
            
            Job: ${{ github.job }}

            Worflow: ${{ github.workflow }}

            Workflow Status: ${{ job.status }}

            Docker Image: ${{ steps.meta.outputs.tags }}-${{ steps.short-sha.outputs.sha }}